import pygame

gameMenu = pygame.image.load("game-menu.jpg")
highscoreMenu = pygame.image.load("highscore-menu.jpg")
regelsnl = pygame.image.load("RegelsNederlands.png")
regelsen = pygame.image.load("RegelsEngels.png")
ship_red_big = pygame.image.load("red-big.png")
ship_red_medium2 = pygame.image.load("red-medium-2.png")
ship_red_medium3 = pygame.image.load("red-medium-3.png")
ship_red_small = pygame.image.load("red-small.png")
ship_blue_big = pygame.image.load("blue-big.png")
ship_blue_medium2 = pygame.image.load("blue-medium-2.png")
ship_blue_medium3 = pygame.image.load("blue-medium-3.png")
ship_blue_small = pygame.image.load("blue-small.png")
dead_ship_red_big = pygame.image.load("x1-p1.png")
dead_ship_red_medium2 = pygame.image.load("x2-p1.png")
dead_ship_red_medium3 = pygame.image.load("x3-p1.png")
dead_ship_red_small = pygame.image.load("x4-p1.png")
dead_ship_blue_big = pygame.image.load("x4-p2.png")
dead_ship_blue_medium2 = pygame.image.load("x2-p2.png")
dead_ship_blue_medium3 = pygame.image.load("x3-p2.png")
dead_ship_blue_small = pygame.image.load("x1-p2.png")
